kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "k8s-to-ai.name" . }}-clusterrole
rules:
  - apiGroups: [""]
    resources: ["pods", "deployments"]
    verbs: ["get", "list"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list"]