kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "k8s-to-ai.name" . }}-clusterrolebinding
subjects:
  - kind: ServiceAccount
    name: {{ include "k8s-to-ai.name" . }}-serviceaccount
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "k8s-to-ai.name" . }}-clusterrole
  apiGroup: rbac.authorization.k8s.io